---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations: {}
  finalizers: []
  labels:
    app: "redis"
  name: "redis-deployment"
  namespace: "default"
  ownerReferences: []
spec:
  replicas: 1
  template:
    metadata:
      annotations: {}
      finalizers: []
      labels:
        app: "redis"
      ownerReferences: []
    spec:
      containers:
      - args: []
        command: []
        env: []                      
        envFrom: []
        image: "redis"
        imagePullPolicy: "IfNotPresent"
        name: "redis-deployment"
        ports:       
        - containerPort: 6379
          name: tcp          
        volumeMounts: []
      hostAliases: []
      imagePullSecrets: []
      initContainers: []
      nodeSelector: {}
      tolerations: []
      volumes: []
